### ISSUE TITLE
Socket error

### ISSUE THREAD

**Issue by torhve** [azurewang/lua-resty-postgres#2]
During benchmarking I got this error:

attempt to receive data on a closed socket: u:0000000040246F30, c:0000000000000000, ft:5 eof:1

And no postgresql commands would work until restart of nginx

**Comment by azurewang** [comment]
Postgresql max_connections is too small,
This error occurs when concurrent exceeds the maximum.
Please set a larger value.
I'll fix the error as soon as possible.

**Comment by azurewang** [comment]
This bug has been fixed
