### ISSUE TITLE
auth return type not support

### ISSUE THREAD

**Issue by leafo** [azurewang/lua-resty-postgres#3]
I'm trying to connect to my Postgres 9.2 server. I tried both password and trust auth and I get the same error when calling `connect`:

``` lua
local pg = require "resty.postgres"
local db = pg:new()
db:connect { host = "127.0.0.1", port = 5432, user = "leafo", database = "leafo", password = "leafo" }
```

returns `nil, "auth return type not support"`

**Comment by azurewang** [comment]
only  support   md5 auth
在 2013-5-20 下午2:51，"leaf" notifications@github.com写道：

**Comment by leafo** [comment]
Ah thanks, I didn't notice md5 auth at first. Works now.
