### ISSUE TITLE
incompatibility with pgbouncer

### ISSUE THREAD

**Issue by gglamenace** [azurewang/lua-resty-postgres#4]
here is the error from pgbouncer.log when trying to connect through pgbouncer:

2013-11-25 14:48:20.152 10075 LOG S-0x15d2270: prplk/admin_postres@127.0.0.1:5431 new connection to server
2013-11-25 14:48:20.156 10075 ERROR C-0x15b48c0: test/admin@127.0.0.1:39868 unknown pkt from client: 112/0x70
2013-11-25 14:48:20.156 10075 LOG C-0x15b48c0: test/admin@127.0.0.1:39868 closing because: unknown pkt (age=0)
2013-11-25 14:48:20.156 10075 WARNING C-0x15b48c0: test/admin@127.0.0.1:39868 Pooler Error: unknown pkt

**Comment by azurewang** [comment]
what's the pgbouncer version and postgresql version?

**Comment by azurewang** [comment]
I'm using postgresql9.2 and pgbouncer-1.5.4,that's OK.
pgbouncer config:
    auth_type = md5
    auth_file = /usr/local/pgbouncer/etc/userlist.txt
lua-resty-postgres only support md5 auth_type

**Comment by azurewang** [comment]
lua-resty-postgres  not support  trust auth_type.

**Comment by gglamenace** [comment]
Hello,

Thank you for your reply, I will use md5.

Best regards
Jérôme

De : AzureWang [mailto:notifications@github.com]
Envoyé : mardi 26 novembre 2013 04:38
À : azurewang/lua-resty-postgres
Cc : gglamenace
Objet : Re: [lua-resty-postgres] incompatibility with pgbouncer (#4)

lua-resty-postgres not support trust auth_type.

—
Reply to this email directly or view it on GitHubhttps://github.com/azurewang/lua-resty-postgres/issues/4#issuecomment-29265283.

[http://www.esker.fr/data/Esker_Logo_Signature.gif]http://www.esker.fr        Jérôme Lafon
Consultant / Professional Services Consultant
Tél : +33 (0)4 72 83 46 46 | Fax : + 33 (0)4 72 83 46 40
jerome.lafon@esker.fr
www.esker.frhttp://www.esker.fr/ | www.flydoc.frhttp://www.flydoc.fr/

[http://www.esker.fr/data/RSS_Icon_Gray.gif]http://www.esker.fr/rss.asp [http://www.esker.fr/data/YouTube_Icon_Gray.gif] http://www.youtube.com/channel/UCRNuK_jrg-GinCQy8B5oAnQ  [http://www.esker.fr/data/Linkedin_Icon_Gray.gif] http://www.linkedin.com/company/esker-france  [http://www.esker.fr/data/Viadeo_Icon_Gray.gif] http://www.viadeo.com/fr/company/esker?ga_from=Fu:/v/companies/followed/;Fb%3ACompanyProfile-CompanySuggest%3Bfe%3ACompanyName  [http://www.esker.fr/data/Twitter_Icon_Gray.gif] http://twitter.com/Eskerfrance  [http://www.esker.fr/data/Google_Icon_Gray.gif] https://plus.google.com/107535011686313719847/posts

CONFIDENTIALITE : Ce message et les éventuelles pièces jointes sont confidentiels. Si vous n'êtes pas dans la liste des destinataires, veuillez informer l'expéditeur immédiatement et ne pas divulguer le contenu à une tierce personne. Les idées et opinions présentées dans ce message sont celles de son auteur, et ne représentent pas nécessairement celles de la société. Par ailleurs et malgré toutes les précautions prises pour éviter la présence de virus dans nos envois, nous vous recommandons de prendre, de votre côté, les mesures permettant d'assurer la non-introduction de virus dans votre système informatique. La société ne saurait être tenue pour responsable de tout dommage causé par la présence d'un virus dans ce message.

---
